<a href="https://colab.research.google.com/github/martinrebane/tehisaru_naited/blob/main/Optimal_braking_time_NN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# A Simple Neural Network

Now let's try to have IseAuto use a neural network for estimating the time it needs to use for smooth braking. We will input initial speed and final speed and expect the network to learn braking time. We are not going to use acceleration any more as this in computed property. But our dataset (which we use for training the neural network) is built so that the acceleration is -0.4 m/s^2.

In [ ]:
import torch
from torch import nn
import torch.nn.functional as F

In [ ]:
# each pytorch NN will extends nn.Module
class BrakingTimeNetwork(nn.Module):
  def __init__(self):
    super().__init__()
    # millised kihid on olemas
    self.my_module = nn.Sequential(nn.Linear(in_features=2, out_features=5),
                               nn.ReLU(),
                               nn.Linear(in_features=5, out_features=12),
                               nn.ReLU(),
                               nn.Linear(in_features=12, out_features=7),
                               nn.ReLU(),
                               nn.Linear(in_features=7, out_features=3),
                               nn.ReLU(),
                               nn.Linear(in_features=3, out_features=1)
                               )

  def forward(self, data):
    # kuidas neid kihte käivitada
    return self.my_module(data)






In [ ]:
# our model
model = BrakingTimeNetwork()

In [ ]:
# initial speed and final speed
speed_data = torch.tensor([[5.07,3.92],
                           [3.0,1.05],
                           [1.99,0.44]])

# ground truth: known true values for time
# essentially these are: (speed_data[:,1] - speed_data[:,0]) / -0.4
brake_time = torch.tensor([[2.8750], [4.8750], [3.8750]])


In [ ]:
# loss function
loss = nn.MSELoss()

# optimiser
optimiser = torch.optim.SGD(model.parameters(), lr=0.01)


In [ ]:
model.train()
# we are going to change epoch count
epochs = 1000
for i in range (0, epochs): # epochs
  # iterate over each row in dataset
  for j in range (0, speed_data.shape[0]):
    # clear the gradients
    optimiser.zero_grad()
    # our batch size is one, we feed in 1 example at the time to observe the change
    # in real applications, batch size is higher

    output = model(speed_data[j])

    iter_loss = loss(output, brake_time[j])

    #print("LOSS", iter_loss)

    # compute gradients
    iter_loss.backward()

    # update model parameters
    optimiser.step()





In [ ]:
for i in range(speed_data.shape[0]):
  print(model(speed_data[i]),brake_time[i])



tensor([2.8750], grad_fn=<ViewBackward0>) tensor([2.8750])
tensor([4.8750], grad_fn=<ViewBackward0>) tensor([4.8750])
tensor([3.8750], grad_fn=<ViewBackward0>) tensor([3.8750])


In [ ]:
out = model(torch.tensor([2.0, 5.0]))
gt = (5 - 1) / -0.4
print(out, gt)


tensor([1.9709], grad_fn=<ViewBackward0>) -10.0


# TODO: Write the validation code!